language: node_js

script:
  - npm run test-travis

services:
  - mongodb

before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
  - "npm install -g npm@3"


before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - "npm install -g gulp"

node_js:
  - "4"
  - "5"
  # configure notifications (email, IRC, campfire etc)
  # please update this section to your needs!
  #notifications:
    #irc: "irc.freenode.org#travis"

after_success:
  - npm run coverage