language: node_js
dist: trusty
sudo: false
cache: yarn
services: mongodb
before_script:
  - ls node_modules
  - which tsc
  - ls `npm bin`
  - sh ./scripts/build.sh
script:
  - sh ./scripts/style-check.sh
  - npm run test --silent
