language: node_js
dist: trusty
sudo: false
services: mongodb
before_script:
  - rm -rf ./node_modules && yarn
  - sh ./scripts/build.sh
script:
  - sh ./scripts/style-check.sh
  - npm run test --silent
cache:
  yarn: false
