import { InterfaceGenerationOptions, version } from './util';

export function generateDefinitionPreamble(
  passedOptions: InterfaceGenerationOptions
) {
  // default date to false so that the file becomes idempotent and doesn't trigger a new github commit
  // everytime it is run
  const opts = Object.assign({ date: false, header: '' }, passedOptions);

  return `${opts.header}/**
 *
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Generated by \`tyranid-tdgen@${version}\`: https://github.com/tyranid-org/tyranid-tdgen
 * ${opts.date ? `date: ${new Date()}` : ''}
 */
  `;
}
