import { version, InterfaceGenerationOptions } from './util';

export function generateDefinitionPreamble(
  passedOptions: InterfaceGenerationOptions
) {
  const opts = Object.assign({ date: true, header: '' }, passedOptions);

  return `${opts.header}/**
 *
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Generated by \`tyranid-tdgen@${version}\`: https://github.com/tyranid-org/tyranid-tdgen
 * ${opts.date ? `date: ${new Date()}` : ''}
 */
  `;
}
